[package]
name = "art"
license = "MIT"
version = "0.1.0"
description = "A test to cargo"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
